####################################
#
# Jupyter
#
####################################

####################################
#
# Prometheus
#
####################################

# Optional - Store Images on a Private Docker Registry
# Prometheus
metrics:
  enabled: false
  port: ""
  endpoint: ""

####################################
#
# Private Docker Registry
#
####################################

# Optional - Store Images on a Private Docker Registry
registry:
  addToSecrets: false
  # user on docker hub:
  # https://cloud.docker.com/u/jayjohnson/repository/docker/jayjohnson/stock-analysis-engine
  address: jayjohnson
  # private docker registry set these:
  # addToSecrets: true
  # address: FQDN:PORT
  # imagePullSecrets: ae.docker.creds.jupyter
  # dockerConfigJSON: '{"auths":{"FQDN:PORT":{"Username":"username","Password":"password","Email":""}}}'

####################################
#
# Secrets
#
####################################

# Minio or AWS
s3_minio:
  addToSecrets: true
  secretName: ae.k8.minio.s3.jupyter
  address: ae-minio:9000
  region: us-east-1
  accessKey: trexaccesskey
  secretKey: trex123321

# AWS S3 West
s3_aws:
  addToSecrets: true
  secretName: ae.k8.aws.s3.jupyter
  address: s3.us-west-2.amazonaws.com
  region: us-west-2
  accessKey: ""
  secretKey: ""

# Redis
redis:
  addToSecrets: true
  secretName: ae.k8.redis.jupyter
  address: ae-redis-master:6379
  pricingDB: 0
  backtesterTaskDB: 11
  backtesterResultDB: 12

####################################
#
# Slack Integration
#
####################################

# Publish Alerts or Notifications to Slack
slack:
  addToSecrets: true
  secretName: ae.k8.slack.jupyter
  webhook: "https://hooks.slack.com/services/YOUR_WEBHOOK_HERE"
  token: ""
  channels: ""
  prodAlerts: "0"
  dataAlerts: "0"

####################################
#
# Analysis Engine Components
#
####################################

# Jupyter Pod
jupyter:
  # comma-delimited list supported for all of these:
  name: ae-jupyter
  namespace: ae
  username: trex
  password: admin
  image:
    private: false
    name: stock-analysis-jupyter
    tag: latest
    pullPolicy: Always
  label: ""
  s3:
    enabled: true
    name: "minio"
    secretName: ae.k8.aws.s3.jupyter
  redis:
    enabled: true
    secretName: ae.k8.redis.jupyter
  slack:
    enabled: false
    secretName: ae.k8.slack.jupyter
  ingressNginx: true
  ingressEnabled: true
  ingressFQDN: aejupyter.example.com
  ingressSecretName: tls.jupyter
  ingressTLSCert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUd2VENDQktXZ0F3SUJBZ0lKQU90cXRXS1BNb2o1TUEwR0NTcUdTSWIzRFFFQkN3VUFNR014Q3pBSkJnTlYKQkFZVEFsVlRNUXN3Q1FZRFZRUUlEQUpEUVRFTk1Bc0dBMVVFQnd3RVEybDBlVEVRTUE0R0ExVUVDZ3dIUlhoaApiWEJzWlRFUU1BNEdBMVVFQ3d3SFJYaGhiWEJzWlRFVU1CSUdBMVVFQXd3TFpYaGhiWEJzWlM1amIyMHdIaGNOCk1UZ3hNakU0TWpJeE56STNXaGNOTVRreE1qRTRNakl4TnpJM1dqQmxNUXN3Q1FZRFZRUUdFd0pWVXpFTE1Ba0cKQTFVRUNBd0NRMEV4RFRBTEJnTlZCQWNNQkVOcGRIa3hFREFPQmdOVkJBb01CMFY0WVcxd2JHVXhFREFPQmdOVgpCQXNNQjBWNFlXMXdiR1V4RmpBVUJnTlZCQU1NRFNvdVpYaGhiWEJzWlM1amIyMHdnZ0lpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQ0R3QXdnZ0lLQW9JQ0FRQ3VoL0d4SVFvRUthMW15RzhUcWlialRmNGhsSGNNN3BONVZkNW8KUnFYclA3TzY3ai9MRHd2UHVHbWJVVjFMWm1tUXI5RTRyNWNYdjBoWUk1cHVjemNVVmlIaWkyZXkyVGxDdnBIZwpDZVFXQ0d2c3R0eVVHR3dGcXV1MEgvNTA3bnExdVI2dDBUSElkVzkyeFlyVUlDMDVpa0xoRmNpWVJxTjVjSHU5Cm5DN1FEcnVyZGpxRkx2MWk5eG9ad2pnNmFIZStISmpRTE9XS1FVVkdkampqck81bVpDbWV1RUZXZkFKSmplcG4KdTFyRHpJT3NFMVFDb1h5dXhScHNZNFlNVENYa0o0TTFjb056YVBvcTlXNWZzREJVbDRRVEF0TFdZRkduMnVuYgpOMndqblpzWFlnblVoWFR3TU9jL3YwcFZTQUNnWTZSMjFJekZEVEpRV3FmZGdycVo0V2w4clNmTUVOY2ptSng4Clk2SFNRZURZRTZ0dVVLQXdXcmQ1WDhhNmpMT2RPcnpPUTdaZlU0VHkwQ1dKOE04b2tWVUx5RWkyM090anJMd3MKT2V6QXdHWjFIS2V0L002S1ZkdmFXWkg3MitMQ0Y0WVJ2Z1lCN3YvendDdTNIVGJPRmwvc0ZWZE4vdmVnYVloUgp0K1FCbDNvZGFxOXRRMGhLOGlzM1hrTFJBRXhtUitOS0NFMC9jQ2VTR0w3R2p4OGdQQ0NlTEMyZ05QR2hvVWNyCmlxZDFPZFlwYk1FYjYzY0VBTzdrK1h5NnUzdWVDVTIvRHNiOTJ5cXhCRTZhWStGSUdUMXZxUmhnOU5GLzVLY0YKR0J6Y3MzdVBMT3ZieVBZRUNnVVVheHNjV1ZpV1NaWmp1NS93TndLZm5GZ1BSTVB3V0JEZEE0MEY2YVhuZW5CdApaSGo2N3dJREFRQUJvNElCY0RDQ0FXd3dnZ0ZUQmdOVkhSRUVnZ0ZLTUlJQlJvSU5LaTVsZUdGdGNHeGxMbU52CmJZSVVjbUZpWW1sMGJYRXVaWGhoYlhCc1pTNWpiMjJDRVhKbFpHbHpMbVY0WVcxd2JHVXVZMjl0Z2hOcWRYQjUKZEdWeUxtVjRZVzF3YkdVdVkyOXRnaE5xWlc1cmFXNXpMbVY0WVcxd2JHVXVZMjl0Z2c5M2QzY3VaWGhoYlhCcwpaUzVqYjIyQ0QyRndhUzVsZUdGdGNHeGxMbU52YllJT1pHSXVaWGhoYlhCc1pTNWpiMjJDRTNCbllXUnRhVzR1ClpYaGhiWEJzWlM1amIyMkNGbkJvY0cxNVlXUnRhVzR1WlhoaGJYQnNaUzVqYjIyQ0VtdHBZbUZ1WVM1bGVHRnQKY0d4bExtTnZiWUlPYkdJdVpYaGhiWEJzWlM1amIyMkNFbVJ2WTJ0bGNpNWxlR0Z0Y0d4bExtTnZiWUlPYXpndQpaWGhoYlhCc1pTNWpiMjJDRW5Od2JIVnVheTVsZUdGdGNHeGxMbU52YllJUmEyRm1hMkV1WlhoaGJYQnNaUzVqCmIyMkNEbk16TG1WNFlXMXdiR1V1WTI5dGh3Ui9BQUFCTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUNNNGlMR0daM1EyVk8zdHJlZ0I2SytTNVg1WGF5RFNXYVBPeHBjRnROUApDR2xmQllMQ3VhK0NzSFlpMUV3VThod0owWkJKUmZTazJ4NVBpeFNhN1VoelNPbVQydFNnZnVZT1MzbGFaR25JCk5vZlNMMTVkNWI5MUppci9uOHhRaXVaaFFSamxFQVJHemw2WGZ6WC8wZVRsMGpUMk1YM0dHNGVvV0lKN3hwTWYKZjRTWFA1bGhUaUJmRWg2UW5WcFc1S0wrUkJzOWsyUGJiSG9QcUZlQVRPZFc5M3lZTHdtdFQ0UEZmTXRuMVJBRgo0S014d3BqbENzeG8vMU5SYXdzYS9xcmtPY1J3YlNENnc4R0c4enU5WEZwazJnZ09jVFg5dkpLSVdCWmdBRzliCjhUYjUwbkkzSGFBMDhNbjRBb01yRE5GRmE1OG1ncTExQUJrNmJDeHc3OUIvSGdGUVhYRExzN3RJbWR2RXdYSHUKS081b2pnSkJtQ3lsaXRvVmJHMW9PdkxIZnllL1NrWXh1b08wRFpjSDk5SmlkcEJXUG5PaVdtYlMwTFNKTXZ1UgpGK01rMUhrRUUwZ0NDMXErQkZZcS9oejh0RDNVRGdOZER2L2NidWlMWlBiRU9VRnFBNm1sdmtPdHpzYjJZTmlnCjdldWlWaFNyQnQ5OWF1Wllpb3dnR2x4Vmltay9DVTdEQ1U4akpOc25PdU05ZzhqWHp2Z3RONlNuRkJtNk50ZUwKeHErUHFDelg1RURpUCtQRGxocGkzT2x5ZEtPK2w2UFJRbUhXQzlBZ0ZBUDljWTV5ZmZOdjJsU2VObGdadlZocQp1dXVKTjYxU08vMnhPcDl3aTRPbi9TMStFeGFBR3A3SVVuU2lYb3dHeTlUVDZucWhlSDJBQUsxS1IyMTMvejc5CjZRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  ingressTLSKey: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBcm9meHNTRUtCQ210WnNodkU2b200MDMrSVpSM0RPNlRlVlhlYUVhbDZ6K3p1dTQvCnl3OEx6N2hwbTFGZFMyWnBrSy9ST0srWEY3OUlXQ09hYm5NM0ZGWWg0b3Ruc3RrNVFyNlI0QW5rRmdocjdMYmMKbEJoc0JhcnJ0Qi8rZE81NnRia2VyZEV4eUhWdmRzV0sxQ0F0T1lwQzRSWEltRWFqZVhCN3Zad3UwQTY3cTNZNgpoUzc5WXZjYUdjSTRPbWgzdmh5WTBDemxpa0ZGUm5ZNDQ2enVabVFwbnJoQlZud0NTWTNxWjd0YXc4eURyQk5VCkFxRjhyc1VhYkdPR0RFd2w1Q2VETlhLRGMyajZLdlZ1WDdBd1ZKZUVFd0xTMW1CUnA5cnAyemRzSTUyYkYySUoKMUlWMDhERG5QNzlLVlVnQW9HT2tkdFNNeFEweVVGcW4zWUs2bWVGcGZLMG56QkRYSTVpY2ZHT2gwa0hnMkJPcgpibENnTUZxM2VWL0d1b3l6blRxOHprTzJYMU9FOHRBbGlmRFBLSkZWQzhoSXR0enJZNnk4TERuc3dNQm1kUnluCnJmek9pbFhiMmxtUis5dml3aGVHRWI0R0FlNy84OEFydHgwMnpoWmY3QlZYVGY3M29HbUlVYmZrQVpkNkhXcXYKYlVOSVN2SXJOMTVDMFFCTVprZmpTZ2hOUDNBbmtoaSt4bzhmSUR3Z25pd3RvRFR4b2FGSEs0cW5kVG5XS1d6QgpHK3QzQkFEdTVQbDh1cnQ3bmdsTnZ3N0cvZHNxc1FST21tUGhTQms5YjZrWVlQVFJmK1NuQlJnYzNMTjdqeXpyCjI4ajJCQW9GRkdzYkhGbFlsa21XWTd1ZjhEY0NuNXhZRDBURDhGZ1EzUU9OQmVtbDUzcHdiV1I0K3U4Q0F3RUEKQVFLQ0FnQmNvcmxORzgwMk1temdMaWlPMW5RM2w3RDRYOVhrbmtqV1VSWndZSGMyYXlSWlpwV2prTVBqSisyZAp5OHpwOVZ5NHVDa2pua2RqQ2xzNnRRTUY5czlZVXZNL1RHRHBFOVVKc1I2NlBHVzhzQkdnbmRwc0hKNVJUOHcxCldmbjBWSlA3R2x2SFJFN1pLRVBXVmJsL0orajVMb0thOTdYMTVTQmxsNmVHRjN6ZFg4U0ttSUV0S2FqQ080ZTEKL2xsYjN4RVhiaFJLQWxwL1RHK1ptNnhNWkFCUmhuNTB5VFdjMHN0Z0FSeFduS0hyWlFUS2M2UFdsYUlaSFhNTgo3ckU2bTd4TTRoQUpjVk9HRVVVZlFnK29hRnJ1dTFFVnloemdQbFY0ODMvR3BCOFl0RkdhVXFZSEVDTG1UZjZmCjNrZDFCbmVXcWV5a1NlTEJ3R1JoTkF6L1RLRC9wTFdwWjk5Umw4dGVsdFhSQkVLai9tQ3JJWHk5UE5XVUY0Ym4KTXE4bzFQd1BIeTZRRk9ZVWdkTTREUVdEVjQyRjcyVlU2NzVKbVhkbkV0S3ZnTzIwNmRGNjAyV1U4ZlkzWjI0QQpBV1dmbzUxMnQwS3JGWk10am9qcVc2TjlGdTB1NWdZakwySWhQV2o5ZHF1MW9nTG5pVmROa2VHSWRjdVZjSm4vClN5L0VOVTlJUVVteGpDV3RZSjhxUk1TeFN2OVRkY3hlYWQ4KzYrL1BEclNNcjVoeW5HTVJZZ0lOSUREN09nS0wKMWRlNW9SUEhMY0MrK09ZWEE3SUxSdlljRUpad3RiYVlvYkw3K3RSTGIzbWYwOVRZb0JKY2FTbkwzVHNUbERIYQpzV2dZRWxHV3lJNmVQRjhPZ09VMks3WWk1WVhoSzhjZ1ErM2RmUVJ3alEyVElRN0NnUUtDQVFFQTZJVnFXcStRCmRncTN5SllWSzg0ZHVXWVRUeEdxbFAzYTY4QVNrenFXQXY2YmZHLzQwM3BpYUNlNE1XVm1waFE3L29wYzZ4MFAKWU1PUWhuQVlZWGN5b1V2b0dyUUNjN3hsUkxuem0zc01ybmpNbFo4aXdMNlZnc2p0WjJybFRTeHh0bWxQNWliVgphTWpPd3dwZ3VIUDFMNHF3ZjdkdFJIL0NBYXd1NlVtQkRJVkJtdFFDZWZOWGd6UDNMTnhyRmpwUkM3UWMzM2x1CjV3dkxGNTduZi9aSzlycys2cnpmWWxLR1Y1Sll2NmhLUWNwditqRlNySUNaZ0VxQzEzQ3dUMVlMS0VSeEl6emcKR0NIdUhEMDY4eTBoOUVlaWRBVEo4WjdveWpwOWIrcm9aUlRoUXNUckFna1hPaDhSWWJicHl0WXNsdEJWcHJNdApja3ZCL0l3bmpRZlByd0tDQVFFQXdDZUJlZHdWUU9jUFI3bGxBSmJSZUhQOG5qYm9FZVZtdmdIbDhkWGFBNzQwCmxMcUtMeWN6cHhQVGlLN0FodXJIZ1JVejliaGpKMlZ4SHBZUlJjYU1MTHNJMk1QZUhQejRCYVlOZFRuWTh6RXoKUGF0Yy8wN3NBR3lmOFU4dElFNzNvdmJCZUpjeW1Ba3BUZThUb0ZPMTIwWkE0SlZ3YXAxRVNBYmVOR2laaEdjdgpuMnhFbDJNU2NHNnI0ck1wRWNEWEVmeDZNRWJUSGJ0ZHp3MkhrR1g2bmpRTTU5VDY3STNGMEdta05TY0dMU0RYCitKc3pOZWxXMWxEcHpqYXJjRDh3c2FnYWZvQXlUUU1DYSs3ek9MeGk0ODA3NzU1eUxUK0JoYWJmL2luQXBIOVgKSWhVTVNHdVBXMEVoalV2aDFuSlZYMU1QUlNOQTRqS2k4Z2ZydmZNWXdRS0NBUUVBaldjdE1XOFpEQ0FpZWZLRApkM3RHYWt3Z0svS1RhVDRqMTBDY1N6clNwWW1PcHhNMUgrNktUOHJ2NGVKSGxYSXl0ZTRRNmM1blhySXZmd0pHCllXZHF1OXA4a1ZpdE1STCtCdGlLeENBRnEwaTlLYlI0SHYwSDBWdzl1Nm12UHNwcmNNSUVtL003enhoblhRYy8Kb0l5c0s3aE04NjVwM2NGUUMxSlp5UGN4YXByVE5jUCtxWWtKekRsYTlNWXF2WDdEY0xtYzRXNW91a3RhdThlZwpBeHFWcGd4akM3L0duWFdRUzBzdGU0aHRlQ3NUQS9UZzBSVDN4S1FMZzliODhaSmpBSjcycXJaSGxZVjAxMm1KCkl2OXNhYkR5bzFtU01jVXd6bUxaaTZrd29PQWN5VTBWbWN4TGVzWVAvUHVPbkJLNVZSSG5OSlE4YkFpVU5QQksKMFNKUjh3S0NBUUJCWCs5OEh6V1g3RVRWbVN6VTQzc0c2U2RFU05meDVzTnExOGg4Mjg0ZHdlT3Z5anRqU1lvWQpTUFdLSmpKWWRKNUZ1NG4vQ3FtcGFLand5QXUrV291c1dFSHRSYzVXdkhaQnJib2NiUDd6MW9SaGNlRGs5OXZ4ClZRT2huTmQwaTRsVEIzTFJiVmVJUkcycUZ6SHROUzNGR1lUUEkraW9UVE5DOGhzOVoyejdrQU95MEtvUmUySjEKb0NHWXNtM0JuWU5PbWtDVUZqU1RoQUNwaGlmZUorUDVXU29lNGVZdy94Y1REaTRRNjJMOWpaUU0vL2lQV2dEeQpUM3NNYnFzck9FUi8zUHFPbVYwRHVJZGxZMW1hcnZWU0hheExuUE9wazFha3V4NndJVkpxWk95bkt0UVArNUE5CmNzNVFmVVdycVNDRW13U3grQW1HSzhZbVpDMS9aYXJCQW9JQkFBUk11d2EyeXVQMFlGRkdyOXFHS0V4MUt0dVQKanE3NjRZV0RhMXpOYUNLamd2YVRWWHNMM25YaGZmTEVDTC8wbktINWU0SmM3anlmVXZTSTQzZFlWUjBnd1RHdgpqVFBTN2JKWld1RXJLa0M3cHhmWGY3VkJpL3hXbEorZFZXdG9iVHFHWkFQVlVvVzM1VGQzWHVnd1lDYnlIQnRMClBSUXRUblpQd2xTK1VnbkhvOEZEY2YxWCt4NE16VE9Kb3NOUWxYcHV4RngzcW5ER1dycWs0dzRkbC9qaDlnSHIKckRlV1ZWTzFvZzloRnBQd3g1WWQ2UHVmVlIxTzN4SDVmYmhEdkFyaHo4bUJ3UXQyVU9Gb2o5Sm0rTHFvT3M2dwpiK2FFYUtDYlZ3ekpybmwzd1p1VjAvOFR2Tzg5RnpCV0FzNnNGcTVKR3lVRExFaGlHV0x4bFd5UHF1ST0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K"
