####################################
#
# Export Cached Ticker Data to S3
#
####################################

####################################
#
# Prometheus
#
####################################

# Optional - Store Images on a Private Docker Registry
# Prometheus
metrics:
  enabled: false
  port: ""
  endpoint: ""

####################################
#
# Private Docker Registry
#
####################################

# Optional - Store Images on a Private Docker Registry
registry:
  addToSecrets: false
  # user on docker hub:
  # https://cloud.docker.com/u/jayjohnson/repository/docker/jayjohnson/stock-analysis-engine
  address: jayjohnson
  # private docker registry set these:
  # addToSecrets: true
  # address: FQDN:PORT
  # imagePullSecrets: ae.docker.creds.backup
  # dockerConfigJSON: '{"auths":{"FQDN:PORT":{"Username":"username","Password":"password","Email":""}}}'

####################################
#
# Secrets
#
####################################

# Minio or AWS
s3_minio:
  addToSecrets: true
  secretName: ae.k8.minio.s3.backup
  address: ae-minio:9000
  region: us-east-1
  accessKey: trexaccesskey
  secretKey: trex123321

# AWS S3 West
s3_aws:
  addToSecrets: true
  secretName: ae.k8.aws.s3.backup
  address: s3.us-west-2.amazonaws.com
  region: us-west-2
  accessKey: ""
  secretKey: ""

# Redis
redis:
  addToSecrets: true
  secretName: ae.k8.redis.backup
  address: ae-redis-master:6379
  pricingDB: 0
  backtesterTaskDB: 11
  backtesterResultDB: 12
  engineTaskDB: 13
  engineResultDB: 14

####################################
#
# Slack Integration
#
####################################

# Publish Alerts or Notifications to Slack
slack:
  addToSecrets: true
  secretName: ae.k8.slack.backup
  webhook: "https://hooks.slack.com/services/YOUR_WEBHOOK_HERE"
  token: ""
  channels: ""
  prodAlerts: "0"
  dataAlerts: "0"

####################################
#
# Analysis Engine Components
#
####################################

# Backup Job
backupToS3:
  # comma-delimited list supported for all of these:
  tickers: SPY,AMZN,TSLA
  name: ae-backup
  namespace: ae
  image:
    private: false
    name: stock-analysis-engine
    tag: latest
    pullPolicy: Always
  label: ""
  backupBucket: ae-stock-datasets
  s3:
    enabled: true
    name: aws
    secretName: ae.k8.aws.s3.backup
  redis:
    enabled: true
    secretName: ae.k8.redis.backup
  slack:
    enabled: false
    secretName: ae.k8.slack.backup
