name: ae-restore
apiVersion: v1
appVersion: "0.0.1"
version: 0.0.1
description: Stock Analysis Engine - Restore Job for deploying the latest backed up pricing data from the ae-backup's S3 bucket back into the kubernetes Redis cluster
home: https://stock-analysis-engine.readthedocs.io/en/latest/
icon: https://i.imgur.com/tw2wJ6t.png
sources:
- https://github.com/AlgoTraders/stock-analysis-engine
- https://github.com/AlgoTraders/stock-analysis-engine/tree/master/helm
- https://github.com/jay-johnson/deploy-to-kubernetes/tree/master/ceph
maintainers:
- name: jayjohnson
  email: jay.p.h.johnson@gmail.com
