version: '2'

services:

  # Analysis Engine
  # Automation Dataset Collector
  ae-dataset-collection:
    container_name: "ae-dataset-collection"
    hostname: "ae-dataset-collection"
    image: jayjohnson/stock-analysis-engine:latest
    tty: true
    env_file:
      - ./envs/dataset_collection.env
    entrypoint: "/bin/sh -c 'cd /opt/sa &&
                 . /opt/venv/bin/activate &&
                 /opt/sa/tools/start-dataset-collection.sh'"
