version: '2'

services:

  # Redis
  redis:
    container_name: "redis"
    hostname: "redis"
    image: redis:4.0.12-alpine
    ports:
      - "6379:6379"
    volumes:
      - /data/redis/data:/data

  # Minio
  minio:
    container_name: "minio"
    hostname: "minio"
    image: minio/minio:latest
    env_file:
      - ./envs/local.env
    ports:
      - "9000:9000"
    volumes:
      - /data/minio/data:/data
    command: "server /data"

  # Analysis Engine
  ae-workers:
    container_name: "ae-workers"
    hostname: "ae-workers"
    image: jayjohnson/stock-analysis-engine:latest
    tty: true
    network_mode: "host"
    depends_on:
      - redis
      - minio
    env_file:
      - ./envs/workers.env
    entrypoint: "/bin/sh -c 'cd /opt/sa &&
                 /opt/sa/start-workers.sh'"

  # AE Backtester
  ae-backtester:
    container_name: "ae-backtester"
    hostname: "ae-backtester"
    image: jayjohnson/stock-analysis-engine:latest
    tty: true
    network_mode: "host"
    depends_on:
      - redis
      - minio
    env_file:
      - ./envs/backtester.env
    entrypoint: "/bin/sh -c 'cd /opt/sa &&
                 . /opt/venv/bin/activate &&
                 /opt/sa/start-workers.sh 4'"

  # Jupyter notebooks, converted noteooks as presentation html slides, and tensorboard
  ae-jupyter:
    container_name: "ae-jupyter"
    hostname: "ae-jupyter"
    image: jayjohnson/stock-analysis-jupyter:latest
    tty: true
    environment:
      # reduce the logs printed to notebooks by loading a custom log config
      - SHARED_LOG_CFG=/opt/sa/analysis_engine/log/error-logging.json
    depends_on:
      - redis
      - minio
    env_file:
      - ./envs/jupyter.env
    volumes:
      # please run this from the repo
      # base directory
      - /data/sa/notebooks:/data/sa/notebooks
    ports:
      - "8888:8888"
      - "8889:8889"
      - "8890:8890"
      - "6006:6006"
    entrypoint: "/opt/sa/docker/jupyter/start-container.sh"

  # Analysis Engine - Dataset Collector
  ae-dataset-collection:
    container_name: "ae-dataset-collection"
    hostname: "ae-dataset-collection"
    image: jayjohnson/stock-analysis-engine:latest
    tty: true
    network_mode: "host"
    env_file:
      - ./envs/dataset_collection.env
    depends_on:
      - redis
      - minio
    entrypoint: "/bin/sh -c 'cd /opt/sa &&
                 . /opt/venv/bin/activate &&
                 /opt/sa/tools/start-dataset-collection.sh'"
