apiVersion: v1
kind: Secret
metadata:
  name: ae.k8.minio.s3
type: Opaque
data:
  # echo -n "${AWS_ACCESS_KEY_ID}" | base64
  # trexaccesskey
  aws_access_key_id: dHJleGFjY2Vzc2tleQ==
  # echo -n "${AWS_SECRET_ACCESS_KEY}" | base64
  # trex123321
  aws_secret_access_key: dHJleDEyMzMyMQ==
  # echo -n "minio-service:9000" | base64
  s3_address: bWluaW8tc2VydmljZTo5MDAw
---
apiVersion: v1
kind: Secret
metadata:
  name: ae.k8.aws.s3
type: Opaque
data:
  # echo -n "${AWS_ACCESS_KEY_ID}" | base64
  aws_access_key_id: SETYOURENCODEDAWSACCESSKEYID
  # echo -n "${AWS_SECRET_ACCESS_KEY}" | base64
  aws_secret_access_key: SETYOURENCODEDAWSSECRETACCESSKEY
  # echo -n "s3.us-east-1.amazonaws.com" | base64
  s3_address: czMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20=
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: ae.docker.creds
  namespace: default
data:
  # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  # kubectl create secret docker-registry ae.docker.creds --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-password> --docker-email=<your-email>
  .dockerconfigjson: SETYOURDOCKERCREDS
---
apiVersion: v1
kind: Secret
metadata:
  name: ae.k8.iex
type: Opaque
data:
  # echo -n "${IEX_TOKEN}" | base64
  pub_token: bm90cmVhbHRva2Vu
  # echo -n "beta" | base64
  version: YmV0YQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: ae.k8.tradier
type: Opaque
data:
  # echo -n "api.tradier.com" | base64
  td_endpoint_api: YXBpLnRyYWRpZXIuY29t
  # echo -n "sandbox.tradier.com" | base64
  td_endpoint_data: c2FuZGJveC50cmFkaWVyLmNvbQ==
  # echo -n "sandbox.tradier.com" | base64
  td_endpoint_stream: c2FuZGJveC50cmFkaWVyLmNvbQ==
  # echo -n "${TD_TOKEN}" | base64
  td_token: SETYOURTDTOKEN
---
apiVersion: v1
kind: Secret
metadata:
  name: ae.k8.slack
type: Opaque
data:
  # echo -n "https://hooks.slack.com/services/YOUR_WEBHOOK_HERE" | base64
  webhook: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvWU9VUl9XRUJIT09LX0hFUkU=
  # echo -n "xoxb-012345678901-012345678901-slackbotaccesstoken012345" | base64
  access_token: eG94Yi0wMTIzNDU2Nzg5MDEtMDEyMzQ1Njc4OTAxLXNsYWNrYm90YWNjZXNzdG9rZW4wMTIzNDU=
  # echo -n "general,random" | base64
  channels: Z2VuZXJhbCxyYW5kb20=
